# The length and width of one region in chunks.
# Changing this while you already have regions will break everything!
regiondimension: 16
chunkratio: 1
map:
  world: world_pvp_2
  # The total radius of the board, has to be multiple of 16 * regiondimension!
  radius: 2560
  center:
  # The center of the board, coordinates have to be multiple of 16!
    x: 0
    z: 0
protection:
  blocks: true
  container: true
  doors: true
  redstone: true
  entities: true
  explosions: true
  use: true
  everything: false