name: ${project.name}
main: de.themoep.clancontrol.ClanControl
version: '${minecraft.plugin.version}'
description: ${project.description}
authors: [Phoenix616]
softdepend: [SimpleClans]
commands:
   BukkitTemplatePlugin:
      aliases: [btp]
      description: Command description.
      usage: /<command>
      permission: BukkitTemplatePlugin.smth
      permission-message: You don't have the permission <permission>
permissions:
   BukkitTemplatePlugin.smth:
      description: Gives permission to the some command
      default: op